GPIO_CONFIG = {
    "VALID_PIN": '0',
    "VALID_DIGITAL_WRITE_VALUE": "HIGH",
    "INVALID_PIN": "16",
    "INVALID_DIGITAL_WRITE_VALUE": "MEDIUM",
    "SUCCESS_RESPONSE": '1',
    "FAILED_RESPONSE": '0',
    "INVALID_PIN_RESPONSE": "Invalid pin value",
    "INVALID_STATE_RESPONSE": "Invalid pin",
    "ANALOG_WRITE_VALUE": "100",
    "ANALOG_READ_PIN": "A0",
    "ANALOG_WRITE_PIN": '0'
}

CREDENTIALS = {
    "API_KEY": "xxxx",
    "DEVICE_ID": "xxxx"
}
